#! /usr/bin/env sh

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

registry_json=$root/tools/BakersRegistryCoreUnfilteredData.json
if [ $# -eq 1 ]; then
    registry_json="$1"
    shift
fi

if [ $# -gt 0 ]; then
    >&2 echo "Too many arguments"
    exit 1
fi

delegates="$(jq -r '.[] | .bakerName, .bakerAccount' < $registry_json | \
  while read -r name; read -r account; do \
    echo "  { .bakerAccount = \"$account\", .bakerName = \"$name\" },"; \
  done)"

cat > "$root"/src/delegates.h <<EOF
#pragma once

#include "types.h"
#include "os.h"

// This file is generated by the ./tools/gen-delegates.sh script.

typedef struct {
  uint8_t bakerAccount[HASH_SIZE_B58];
  char* bakerName;
} named_delegate_t;

static const named_delegate_t named_delegates[] = {
$delegates
};
EOF
