#! /usr/bin/env nix-shell
#! nix-shell -i bash -p jq

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel)"
bakers="$(jq -r '.[] | .bakerName, .bakerAccount' < $root/tools/BakersRegistryCoreUnfilteredData.json | \
  while read -r name; read -r account; do \
    echo "  { .bakerAccount = \"$account\", .bakerName = \"$name\" },"; \
  done)"

cat > "$root"/src/delegates.h <<EOF
#pragma once

#include "types.h"
#include "os.h"

// This file is generated by the ./tools/gen-delegates.sh script.

typedef struct {
  uint8_t bakerAccount[HASH_SIZE_B58];
  char* bakerName;
} named_baker;

static const named_baker bakers[] = {
$bakers
};
EOF
